<a href="https://colab.research.google.com/github/Manujk-123/Marvel-Task-Level-1/blob/main/Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define a small array
small_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Repeat the small array to form a larger array
# Here, we repeat it 5 times along axis 0 and 3 times along axis 1
repeated_array = np.tile(small_array, (5, 3))

print("Repeated Array:\n", repeated_array)
import numpy as np

# Define the shape of the array
shape = (2, 5)  # For example, a 2x5 array

# Generate an array with element indexes
index_array = np.arange(np.prod(shape)).reshape(shape)

print("Index Array:\n", index_array)


Repeated Array:
 [[ 1  2  3  4  5  1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10  6  7  8  9 10]
 [ 1  2  3  4  5  1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10  6  7  8  9 10]
 [ 1  2  3  4  5  1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10  6  7  8  9 10]
 [ 1  2  3  4  5  1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10  6  7  8  9 10]
 [ 1  2  3  4  5  1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10  6  7  8  9 10]]
Index Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
